background {
    monitor =

    #path = $HOME/.wallpapers/red-samurais-rp.png
	path = $HOME/.wallpapers/quasar.png

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_size = 2
    blur_passes = 1 # 0 disables blurring
    noise = 0.0017
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    #color = rgba(246,118,143,1)
    color =  rgba(220, 245, 255, 0.95)
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 220
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
	#color =rgba(246,118,143,1)
    color =  rgba(220, 245, 255, 0.95)
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 80
    halign = center
    valign = center
}
rgba(122,162,247,1)
# Today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
	#color = rgba(43,194,222,1)
    color = rgba(180, 210, 230, 0.85)

    font_size = 22
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -30
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
	#color = rgba(43,194,222,1)
    color = rgba(150, 180, 200, 0.75)
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -60
    halign = center
    valign = center
}

# MSG
label {
    monitor =
    #text = cmd[update:18000000] echo "<b>Feels like<big> $(curl -s 'wttr.in?format=%t' | tr -d '+') </big></b>"
    text = cmd[update:18000000] echo "Welcome "${USER^^}""

	#color = rgba(158,206,106,1)
	color = rgba(200, 230, 255, 0.9)
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10

    position = 0, 40
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3

    dots_size = 0.26 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 22
	#outer_color = rgba(0,255,0,1.0)
    outer_color = rgba(25, 35, 50, 0.6)
    inner_color = white
    font_color = black 
    fade_on_empty = true
    placeholder_text = <i>Password...</i> # Text rendered in the input box when it's empty.

    position = 0, 120
    halign = center
    valign = bottom
}
